# Generated by Django 4.1.2 on 2022-11-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='paciente',
        ),
    ]
