# Generated by Django 4.1.2 on 2022-11-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_usuario_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Telefono'),
        ),
    ]
