# Generated by Django 4.1.2 on 2022-11-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_consulta_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'consulta', 'verbose_name_plural': 'consultas'},
        ),
    ]
